import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Manrope } from "next/font/google";
import NavBar from "@/components/NavBar";

// fonts to consider: manrope, poppins
const manRopeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manRopeSans.variable} antialiased min-h-screen bg-black py-5 px-5 sm:px-10 md:px-20 lg:px-24 flex flex-col items-center`}
        // className={`${geistSans.variable} ${geistMono.variable} ${elza} antialiased min-h-screen bg-black p-5`}
      >
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
